### ISSUE TITLE
User defined functions are not included

### ISSUE THREAD

**Issue by QAnders** [AndrewSales/XQS#25]
Ok, so first a disclaimer; I'm not very well-versed in Schematron... We are kind of forced to use it as we run Peppol (peppol.eu) and we have a Java implementation based upon [ph-schematron](https://github.com/phax/ph-schematron) but as some Peppol Schematron rules are fairly complex we suffer performance issues on some larger files (invoices whit many invoice lines as the Schematron calculates (sums) amounts from lines to a total).

I've been hunting another way of running the Schematron validations and my first initial tests using XQuery is promising (compared to Java), but when I wanted to try the actual Peppol files it doesn't seem to work right...
I'm sure I am missing something, but here goes...

The first SCH is this one: https://raw.githubusercontent.com/OpenPEPPOL/peppol-bis-invoice-3/master/rules/sch/CEN-EN16931-UBL.sch
I am able to compile it successfully, but I'd expect an error from it as it has a validation error, however executing either:
```shell
basex -buri=test1.xml -bschema=CEN-EN16931-UBL.sch evaluate.bxs

basex -bschema=CEN-EN16931-UBL.xqy -buri=test1.xml validate.bxs
```
just outputs:
```xml
<svrl:schematron-output xmlns:svrl="http://purl.oclc.org/dsdl/svrl">
  <svrl:ns-prefix-in-attribute-values prefix="ext" uri="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"/>
  <svrl:ns-prefix-in-attribute-values prefix="cbc" uri="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"/>
  <svrl:ns-prefix-in-attribute-values prefix="cac" uri="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"/>
  <svrl:ns-prefix-in-attribute-values prefix="qdt" uri="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDataTypes-2"/>
  <svrl:ns-prefix-in-attribute-values prefix="udt" uri="urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2"/>
  <svrl:ns-prefix-in-attribute-values prefix="cn" uri="urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2"/>
  <svrl:ns-prefix-in-attribute-values prefix="ubl" uri="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"/>
  <svrl:ns-prefix-in-attribute-values prefix="xs" uri="http://www.w3.org/2001/XMLSchema"/>
  <svrl:active-pattern id="UBL-model"/>
  <svrl:fired-rule context="/ubl:Invoice/cac:LegalMonetaryTotal/cbc:PayableAmount"/>
  <svrl:active-pattern id="UBL-syntax"/>
  <svrl:fired-rule context="//cac:PostalAddress | //cac:Address"/>
  <svrl:active-pattern id="Codesmodel"/>
</svrl:schematron-output>
```

The second SCH, this one: https://raw.githubusercontent.com/OpenPEPPOL/peppol-bis-invoice-3/master/rules/sch/PEPPOL-EN16931-UBL.sch

When running that as `evaluate` it gives me no error either, and I can also compile it successfully, but then trying to run the compile schema it is missing some functions;
```shell
/XQS-0.2.0-balisage/validate.bxs, 71/440:
[XPST0017] Unknown function: u:slack.
```

So, what is this n00b missing?

[test1.xml.txt](https://github.com/AndrewSales/XQS/files/15245061/test1.xml.txt)

**Comment by AndrewSales** [comment]
Hello there - thanks for trying out XQS! It helps to understand how it might be used and to hopefully bring it out of alpha sooner.

For your first schema, note that XQS evaluates rule context attributes against the document root, so the pattern `foo` will match any `foo` element in an XSLT implementation, but only if that element is the root element with XQS. The SVRL report shows that only those contexts with an absolute path have matched.

The functions present in the second schema are XSLT ones, but XQS can only handle XQuery functions, which also need to be in the XQuery namespace, `http://www.w3.org/2012/xquery`. I'll add this information to the documentation.

Hope that helps.

**Comment by AndrewSales** [comment]
Just to add, I added a troubleshooting section to the documentation, based on your queries, via https://github.com/AndrewSales/XQS/commit/a39113533ec5ca14db7d48a29f51aff200befdb8.

**Comment by QAnders** [comment]
Thanks! Much appreciated and educational!

As we are getting the Schematrons provided from Peppol, and we must adhere to them as-is I don't see XQuery as an option right now unfortunately...
